{"created": 1760626112.3259661, "duration": 0.03329110145568848, "exitcode": 1, "root": "/Users/ehtesham/Developer/aadhaar-api-test-poc", "environment": {}, "summary": {"error": 5, "total": 5, "collected": 5}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/test_aadhaar_api_v15.py", "type": "Module"}]}, {"nodeid": "tests/test_aadhaar_api_v15.py", "outcome": "passed", "result": [{"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_demographics_invalid_payload", "type": "Function", "lineno": 35}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_demographics_success", "type": "Function", "lineno": 46}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_demographics_unauthorized", "type": "Function", "lineno": 57}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_verify_invalid_payload", "type": "Function", "lineno": 67}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_verify_success", "type": "Function", "lineno": 78}]}], "tests": [{"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_demographics_invalid_payload", "lineno": 35, "outcome": "error", "keywords": ["test_aadhaar_demographics_invalid_payload", "test_aadhaar_api_v15.py", "tests", "aadhaar-api-test-poc", ""], "setup": {"duration": 0.00013516750186681747, "outcome": "failed", "longrepr": "file /Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py, line 36\n  def test_aadhaar_demographics_invalid_payload(session):\nE       fixture 'session' not found\n>       available fixtures: _session_event_loop, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, event_loop, event_loop_policy, include_metadata_in_junit_xml, json_metadata, metadata, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tests/test_aadhaar_api_v15.py::<event_loop>, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py:36"}, "teardown": {"duration": 5.450006574392319e-05, "outcome": "passed"}}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_demographics_success", "lineno": 46, "outcome": "error", "keywords": ["test_aadhaar_demographics_success", "test_aadhaar_api_v15.py", "tests", "aadhaar-api-test-poc", ""], "setup": {"duration": 6.849970668554306e-05, "outcome": "failed", "longrepr": "file /Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py, line 47\n  def test_aadhaar_demographics_success(session):\nE       fixture 'session' not found\n>       available fixtures: _session_event_loop, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, event_loop, event_loop_policy, include_metadata_in_junit_xml, json_metadata, metadata, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tests/test_aadhaar_api_v15.py::<event_loop>, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py:47"}, "teardown": {"duration": 4.079192876815796e-05, "outcome": "passed"}}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_demographics_unauthorized", "lineno": 57, "outcome": "error", "keywords": ["test_aadhaar_demographics_unauthorized", "test_aadhaar_api_v15.py", "tests", "aadhaar-api-test-poc", ""], "setup": {"duration": 5.7124532759189606e-05, "outcome": "failed", "longrepr": "file /Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py, line 58\n  def test_aadhaar_demographics_unauthorized(session):\nE       fixture 'session' not found\n>       available fixtures: _session_event_loop, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, event_loop, event_loop_policy, include_metadata_in_junit_xml, json_metadata, metadata, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tests/test_aadhaar_api_v15.py::<event_loop>, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py:58"}, "teardown": {"duration": 3.8582831621170044e-05, "outcome": "passed"}}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_verify_invalid_payload", "lineno": 67, "outcome": "error", "keywords": ["test_aadhaar_verify_invalid_payload", "test_aadhaar_api_v15.py", "tests", "aadhaar-api-test-poc", ""], "setup": {"duration": 5.249958485364914e-05, "outcome": "failed", "longrepr": "file /Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py, line 68\n  def test_aadhaar_verify_invalid_payload(session):\nE       fixture 'session' not found\n>       available fixtures: _session_event_loop, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, event_loop, event_loop_policy, include_metadata_in_junit_xml, json_metadata, metadata, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tests/test_aadhaar_api_v15.py::<event_loop>, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py:68"}, "teardown": {"duration": 3.78340482711792e-05, "outcome": "passed"}}, {"nodeid": "tests/test_aadhaar_api_v15.py::test_aadhaar_verify_success", "lineno": 78, "outcome": "error", "keywords": ["test_aadhaar_verify_success", "test_aadhaar_api_v15.py", "tests", "aadhaar-api-test-poc", ""], "setup": {"duration": 5.7374127209186554e-05, "outcome": "failed", "longrepr": "file /Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py, line 79\n  def test_aadhaar_verify_success(session):\nE       fixture 'session' not found\n>       available fixtures: _session_event_loop, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, event_loop, event_loop_policy, include_metadata_in_junit_xml, json_metadata, metadata, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tests/test_aadhaar_api_v15.py::<event_loop>, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/Users/ehtesham/Developer/aadhaar-api-test-poc/tests/test_aadhaar_api_v15.py:79"}, "teardown": {"duration": 4.941597580909729e-05, "outcome": "passed"}}]}